apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fulcio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fulcio
    app.kubernetes.io/part-of: fulcio
  name: fulcio
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: fulcio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fulcio
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/securesign-tenant/fulcio/fulcio@sha256:c6e1773eaeb8a5b232c5a619ae74737a07e506142e2b4cc5b78453701cc5d2f5
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 5555
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
