apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fulcio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fulcio
    app.kubernetes.io/part-of: fulcio
  name: fulcio
spec:
  ports:
  - port: 5555
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: fulcio
status:
  loadBalancer: {}
