apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fulcio
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/securesign-tenant/fulcio/fulcio@sha256:c6e1773eaeb8a5b232c5a619ae74737a07e506142e2b4cc5b78453701cc5d2f5
        name: container-image
        resources: {}
status: {}
