apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fulcio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fulcio
    app.kubernetes.io/part-of: fulcio
  name: fulcioqivo
spec:
  port:
    targetPort: 5555
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fulcio
    weight: 100
status: {}
